### ISSUE TITLE
The D2Coding has been updated to 1.2.

### ISSUE THREAD

**Issue by youngminz** [daehyeok/D2Coding-Font-for-Powerline#1]
Hello :) 

The D2Coding has been updated to 1.2. Can you patch the updated font? (the repo has migrated to https://github.com/naver/d2codingfont)

Thank you for publishing patched D2Coding font!

**Comment by daehyeok** [comment]
Patch applied.
I appreciate that let me know new version. but be carefully use. i just automatically patch with fontpatcher. i'm not tested/verified that font.
